name: tf_gpu
channels:
  - defaults
dependencies:
  - python==3.8.10
  - cudatoolkit
  - cudnn
  - pip
  - pip:
      - tensorflow-gpu
      - tensorflow_datasets
      - wandb
      - pylint
      - flake8
      - black